version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "browser",
    "nodejs",
    "vitest"
  ]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"