version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: vibeforge-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vibeforge-network

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: vibeforge-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
    environment:
      - ALLOW_RESET=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vibeforge-network

networks:
  vibeforge-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local
  chroma-data:
    driver: local 